server:
  port: 8080

mongodb:
  client-uri: mongodb://fanggeek:fanggeek!%40#prod@dds-wz9bb4b16e126c042.mongodb.rds.aliyuncs.com:3717,dds-wz9bb4b16e126c041.mongodb.rds.aliyuncs.com:3717/fanggeek?replicaSet=mgset-2456873
  database: fanggeek
  connections-per-host: 50

# redis数据库连接配置(covert)
redisconfig:
  agentUrl: "redis://:YxtIeeNH5ccFgAOAyDnf9UQMAQLiAa@r-wz993be4ef7e2374.redis.rds.aliyuncs.com:6379/115"
  userUrl: "redis://:YxtIeeNH5ccFgAOAyDnf9UQMAQLiAa@r-wz993be4ef7e2374.redis.rds.aliyuncs.com:6379/117"
  # 最大实例数
  maxTotal: 200
  # 最大空闲实例数
  maxIdle: 50
  # (创建实例时)最大等待时间
  maxWaitMillis: 10000
  # (创建实例时)是否验证
  testOnBorrow: true

common:
  envName: prod