server:
  port: 8080

mongodb:
  client-uri: mongodb://fanggeek:fanggeek!%40#dev@dds-wz9d69c504cfac541167-pub.mongodb.rds.aliyuncs.com:3717,dds-wz9d69c504cfac542123-pub.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-4721611
  database: fanggeek

# redis数据库连接配置(covert)
redisconfig:
  agentUrl: "redis://192.168.2.100:6379/3"
  userUrl: "redis://192.168.2.100:6379/4"
  # 最大实例数
  maxTotal: 200
  # 最大空闲实例数
  maxIdle: 50
  # (创建实例时)最大等待时间
  maxWaitMillis: 10000
  # (创建实例时)是否验证
  testOnBorrow: true

common:
  envName: local