server:
  port: 8080

mongodb:
  client-uri: mongodb://fanggeek_be_monitor:fanggeek!%40#dev@dds-wz9d69c504cfac541501-pub.mongodb.rds.aliyuncs.com:3717,dds-wz9d69c504cfac542466-pub.mongodb.rds.aliyuncs.com:3717/fanggeek?replicaSet=mgset-4721611
  database: fanggeek
  connections-per-host: 50

common:
  envName: local

apollo:
  bootstrap:
    enabled: true
  meta: http://apollo-meta.xiaoluxuanfang.com
  cacheDir: /opt
  
app:
  id: dev-mongo-monitor

